AWSTemplateFormatVersion: '2010-09-09'
Description: Test Redshift cluster - minimal cost configuration

Parameters:
  ClusterIdentifier:
    Type: String
    Default: redshift-test-cluster
    Description: Unique identifier for the Redshift cluster
  
  MasterUsername:
    Type: String
    Default: awsuser
    Description: Master username for Redshift cluster
  
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: Master password (min 8 characters)
    Default: TestPass123
    MinLength: 8

Resources:
  # IAM Role for Redshift to access S3
  RedshiftIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  # Redshift Cluster - Single Node ra3.xlplus (modern serverless-like option)
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    DeletionPolicy: Delete
    Properties:
      ClusterIdentifier: !Ref ClusterIdentifier
      DBName: dev
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      NodeType: ra3.xlplus
      ClusterType: single-node
      IamRoles:
        - !GetAtt RedshiftIAMRole.Arn
      PubliclyAccessible: true
      Encrypted: true
      Port: 5439
      AutomatedSnapshotRetentionPeriod: 1
      Tags:
        - Key: Name
          Value: !Ref ClusterIdentifier
        - Key: Environment
          Value: Test

Outputs:
  ClusterEndpoint:
    Description: Redshift cluster endpoint
    Value: !GetAtt RedshiftCluster.Endpoint.Address
  
  ClusterPort:
    Description: Redshift cluster port
    Value: !GetAtt RedshiftCluster.Endpoint.Port
  
  JDBCConnectionString:
    Description: JDBC connection string
    Value: !Sub 'jdbc:redshift://${RedshiftCluster.Endpoint.Address}:${RedshiftCluster.Endpoint.Port}/dev'
  
  RedshiftIamRoleArn:
    Description: IAM role ARN for S3 access
    Value: !GetAtt RedshiftIAMRole.Arn

